gotify_token: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    65646565663931623964613964616638343135333037303863633537333538633335643661623065
    3137396136613266666639363731646239636461336636380a323030613238313138323763333733
    39323739633636333831313031336435323564613736633534626266623662326263646633313434
    6437313231326465620a323038646466303663373930353335326361306535386335376466653232
    3735

paperless_smb_password: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    34653832396634353637643234373061663134356539363266386530623633346664613162636564
    6131623138313165393030336637646363303638396533640a663630656132376530353664366162
    33393963393536633032316339366438613631393037633831613834376137313562653762626238
    3239623962346564320a616464343030633666316433346564616436313339333063636634396233
    3065