gotify_token: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    65646565663931623964613964616638343135333037303863633537333538633335643661623065
    3137396136613266666639363731646239636461336636380a323030613238313138323763333733
    39323739633636333831313031336435323564613736633534626266623662326263646633313434
    6437313231326465620a323038646466303663373930353335326361306535386335376466653232
    3735
